[package]
name = "compress"
version = "0.1.0"
authors = ["Albrecht Naumann <albrecht.naumann@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
